/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.Ste3et_C0st.furniture.java-conventions")
}

dependencies {
    implementation(project(":Core"))
    implementation(project(":PlotSquaredV3"))
    implementation(project(":PlotSquaredV4"))
    implementation(project(":PlotSquaredV5"))
    implementation(project(":PlotSquaredV6"))
    implementation(project(":LocalLibary"))
}

the<JavaPluginExtension>().toolchain {
    languageVersion.set(JavaLanguageVersion.of(8))
}

description = "Dist"
