/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "ProtectionLib"

include(":Core")
include(":PlotSquaredV6")
include(":PlotSquaredV5")
include(":PlotSquaredV4")
include(":PlotSquaredV3")
include(":LocalLibary")
include(":Dist")
