/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.Ste3et_C0st.furniture.java-conventions")
}

repositories {
    mavenCentral()
    maven {
        name = "IntellectualSites Releases"
        url = uri("https://mvn.intellectualsites.com/content/repositories/releases/")
    }
    maven {
        name = "IntellectualSites Snapshots"
        url = uri("https://mvn.intellectualsites.com/content/repositories/snapshots/")
    }
    maven {
        name = "sk89q-repo"
        url = uri("https://maven.enginehub.org/repo/")
    }
}

dependencies {
    implementation(project(":Core"))
    compileOnly("com.sk89q.worldedit:worldedit-core:7.0.0")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.0.4-SNAPSHOT")
    compileOnly("com.plotsquared:PlotSquared-Core:5.13.11")
    compileOnly("com.plotsquared:PlotSquared-Bukkit:5.13.11")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

description = "PlotSquaredV5"
