/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.Ste3et_C0st.furniture.java-conventions")
}

repositories{
    maven { url = uri("https://jitpack.io/") }
    maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots" )}
    maven { url = uri("https://oss.sonatype.org/content/repositories/central" )}
    maven { url = uri("https://maven.enginehub.org/repo/")}
    maven { url = uri("https://papermc.io/repo/repository/maven-public/")}
    maven { url = uri("https://repo.codemc.org/repository/maven-public/")}
}

dependencies {
    compileOnly("com.github.TechFortress:GriefPrevention:16.17.1")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7")
    compileOnly("com.github.bloodmc:GriefdefenderAPI:dd5aa2224c")
    compileOnly("com.iridium:IridiumSkyblock:3.1.1")
    compileOnly("com.github.TownyAdvanced:Towny:0.96.7.0")
    compileOnly("com.github.cryptomorin:kingdoms:1.10.19.2")
    compileOnly("com.github.Ste3et:DiceChunk:160a1fa984")
    compileOnly("com.github.rlf:uSkyBlock-API:2.6.4")
    compileOnly("br.net.fabiozumbi12.RedProtect:RedProtect-Core:7.7.3")
    compileOnly("com.massivecraft:Factions:1.6.9.5-U0.5.23")
    compileOnly("world.bentobox:bentobox:1.16.0-SNAPSHOT")
    compileOnly("com.github.Angeschossen:LandsAPI:4.6.19")
    compileOnly("com.github.OmerBenGera:SuperiorSkyblockAPI:b7")
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.3.0-SNAPSHOT")
    compileOnly("biz.princeps:landlord-core:4.351")
}

description = "Core"
