/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://nexus.iridiumdevelopment.net/repository/maven-releases/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://raw.github.com/FabioZumbi12/RedProtect/mvn-repo/")
    }

    maven {
        url = uri("https://raw.github.com/rlf/uSkyBlock/mvn-repo/")
    }

    maven {
        url = uri("https://ci.ender.zone/plugin/repository/everything/")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://nexus.savagelabs.net/repository/maven-releases/")
    }

    maven {
        url = uri("https://eldonexus.de/repository/maven-releases/")
    }

    maven {
        url = uri("https://mvn.intellectualsites.com/content/groups/public/")
    }

    maven {
        url = uri("https://mvn.intellectualsites.com/content/repositories/releases/")
    }

    maven {
        url = uri("https://mvn.intellectualsites.com/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.mikeprimm.com/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("http://ci.athion.net/job/PlotSquared/ws/mvn/")
    }
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.17.1-R0.1-SNAPSHOT")
}

group = "de.Ste3et_C0st.furniture"
version = "1.3"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
