/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("de.Ste3et_C0st.furniture.java-conventions")
}

dependencies {
    implementation(project(":Core"))
    implementation(files("/lib/AreaShop.jar"))
    implementation(files("/lib/FactionsLegacy.jar"))
    implementation(files("/lib/MassiveCore.jar"))
    implementation(files("/lib/MyChunk.jar"))
    implementation(files("/lib/Residence4.8.4.4.jar"))
    implementation(files("/lib/IridiumSkyblock.jar"))
    implementation(files("/lib/IslandWorld.jar"))
    implementation(files("/lib/RedProtect-7.7.2-b357-Universal.jar"))
    implementation(files("/lib/PreciousStones-10.7.2.jar"))
    implementation(files("/lib/askyblock.jar"))
}

description = "LocalLibary"
